### PR TITLE
Shuffle instance function

### PR DESCRIPTION
**Pull request by mmghannam**

### CODE REVIEW

**Comment by CharJon** [comment]
I think we should add a testcase, that checks if writeProblem produces two different files.

**Comment by CharJon** [comment]
Also, I see a downside of this approach vs the model being shuffled before hand.
If the shuffle is done by the parameters, calling "resetParams" on the model kind of removes the shuffle, which might be unexpected.

**Comment by CharJon** [comment]
I'm not sure, if we should keep the test that uses optimize to check if shuffling works.

- It heavily depends on the yang instances and therefore has hidden side effects: If the yang implementation changes and the problem becomes easy (1 node) the test fails, even if shuffling might work.
- We are testing if the solution process changes and not if shuffling works. So from a testing theory perspective we are testing the wrong thing.
- It is slow (for a test).

If we want to keep a test like this, we should have a persistent test file in e.g. data/test-data

**Comment by mmghannam** [comment]
> I'm not sure, if we should keep the test that uses optimize to check if shuffling works.
> 
> * It heavily depends on the yang instances and therefore has hidden side effects: If the yang implementation changes and the problem becomes easy (1 node) the test fails, even if shuffling might work.
> * We are testing if the solution process changes and not if shuffling works. So from a testing theory perspective we are testing the wrong thing.
> * It is slow (for a test).
> 
> If we want to keep a test like this, we should have a persistent test file in e.g. data/test-data

I agree, I will remove it.

**Pull request merged**
