### PR TITLE
Graph Coloring Formulations

### LINKED ISSUE #63: Graph Coloring

### PR DESCRIPTION
**Pull request by mmghannam**
closes #63

### CODE REVIEW

**Comment by CharJon** [comment]
There seems to be a bug with the partial ordering formulations. I added a test case that uses a benchmark file from [here](https://sites.google.com/site/graphcoloring/vertex-coloring) and it fails. Could you please check this?
I did not upload the file because of possible copyright issues. Maybe we can exchange it for more complex graphs from networkx.

**Comment by CharJon** [comment]
> There seems to be a bug with the partial ordering formulations. I added a test case that uses a benchmark file from [here](https://sites.google.com/site/graphcoloring/vertex-coloring) and it fails. Could you please check this?
> I did not upload the file because of possible copyright issues. Maybe we can exchange it for more complex graphs from networkx.

It's the node lablings fault. We should again make use of nx.convert_node_labels_to_integers(g, 0)

**Comment by mmghannam** [comment]
> > There seems to be a bug with the partial ordering formulations. I added a test case that uses a benchmark file from [here](https://sites.google.com/site/graphcoloring/vertex-coloring) and it fails. Could you please check this?
> > I did not upload the file because of possible copyright issues. Maybe we can exchange it for more complex graphs from networkx.
> 
> It's the node lablings fault. We should again make use of nx.convert_node_labels_to_integers(g, 0)

Should we use this conversion internally in the function?

**Comment by CharJon** [comment]
> > > There seems to be a bug with the partial ordering formulations. I added a test case that uses a benchmark file from [here](https://sites.google.com/site/graphcoloring/vertex-coloring) and it fails. Could you please check this?
> > > I did not upload the file because of possible copyright issues. Maybe we can exchange it for more complex graphs from networkx.
> > 
> > 
> > It's the node lablings fault. We should again make use of nx.convert_node_labels_to_integers(g, 0)
> 
> Should we use this conversion internally in the function?

I think so. This also again makes sure there are no naming problems (as in the other one).

**Pull request merged**
